image: maven:3-jdk-8

stages:
  - build
  - package

only:
  - master

build:
  tags:
    - gitlab-org
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install compile

package:
  tags:
    - gitlab-org
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS clean package -Dmaven.test.skip=true
  artifacts:
    name: "CashEvents"
    paths:
      - target/*.jar